// This file is auto-generated by @hey-api/openapi-ts

export const $Bot = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        context: {
            anyOf: [
                {
                    type: 'object'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Context'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        creator_id: {
            type: 'string',
            format: 'uuid',
            title: 'Creator Id'
        },
        creator: {
            '$ref': '#/components/schemas/User'
        }
    },
    type: 'object',
    required: ['name', 'id', 'creator_id', 'creator'],
    title: 'Bot'
} as const;

export const $User = {
    properties: {
        clerk_id: {
            type: 'string',
            title: 'Clerk Id'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        bots: {
            items: {
                '$ref': '#/components/schemas/Bot'
            },
            type: 'array',
            title: 'Bots',
            default: []
        }
    },
    type: 'object',
    required: ['clerk_id', 'id', 'is_active'],
    title: 'User'
} as const;