// This file is auto-generated by @hey-api/openapi-ts

export type Bot = {
    name: string;
    context?: {
    [key: string]: unknown;
} | null;
    id: string;
    creator_id: string;
    creator: User;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type User = {
    clerk_id: string;
    id: string;
    is_active: boolean;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type UserMeGetResponse = User;

export type BotBotGetResponse = Bot;

export type DeleteBotBotDeleteResponse = unknown;

export type StreamChatChatGetData = {
    message: string;
};

export type StreamChatChatGetResponse = unknown;

export type $OpenApiTs = {
    '/me': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: User;
            };
        };
    };
    '/bot': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Bot;
            };
        };
        delete: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/chat': {
        get: {
            req: StreamChatChatGetData;
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
};