// This file is auto-generated by @hey-api/openapi-ts

export type Bot = {
    name: string;
    context?: {
    [key: string]: unknown;
} | null;
    id: string;
    creator_id: string;
    creator: User;
};

export type User = {
    clerk_id: string;
    id: string;
    is_active: boolean;
    bots?: Array<Bot>;
};

export type UserMeGetResponse = User;

export type $OpenApiTs = {
    '/me': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: User;
            };
        };
    };
};